version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microdb
    ports:
      - "5432:5432"
    networks:
      - micros-net

  products-service:
    build:
      context: ./modules/products-service
    container_name: products-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/microdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PRODUCTS_API_KEY: key
    ports:
      - "8081:8080"
    depends_on:
      - postgres-db
    networks:
      - micros-net

  inventory-service:
    build:
      context: ./modules/inventory-service
    container_name: inventory-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/microdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      INVENTORY_API_KEY: key-inventory
      PRODUCTS_API_KEY: key
      PRODUCTS_HOST: http://products-service:8080
    ports:
      - "8082:8081"
    depends_on:
      - postgres-db
    networks:
      - micros-net

networks:
  micros-net:
    driver: bridge
